---
title: 检测硬件断点
date: 2023-11-07 16:30
author: CHA.ATY
tags:
  - C
  - Windows
  - 断点
---

![](https://img.shields.io/badge/C-17-green.svg) ![](https://img.shields.io/badge/C++-17-green.svg)
![](https://img.shields.io/badge/visual_studio-2019-green.svg)
![](https://img.shields.io/badge/Windows10-22H2_19045.3570-green.svg)

# 一、前言

有矛必有盾，有盾必有矛。

---

# 二、方法一

GetThreadContext就是SetThreadContext的盾，把调试寄存器取过来送纪委检查检查就知道有没有人在干坏事了。  

用这个API来获取当前线程的环境，肯定有人要问为什么是线程，不是进程，不是啥啥啥的。因为在操作系统中，线程才是真正执行代码流程的东西，进程只是一个分配资源的概念，而每个代码执行的时候，自己的寄存器或多或少都会受到影响，简单来说就是线程才能实实在在执行代码，如果用进程的话每个线程都会受到影响，而且进程也没有这个GetProcessContext得到进行环境寄存器的API。

---

# 三、方法二

其实同样是用方法2设置硬件断点的手段，只不过在SEH的异常处理函数中用_pstContext取调试寄存器送纪委就是了，当然用SEH只能检测当前线程的，要检测整个程序的还是用VEH好，方法类似。

采用SEH来处理

```text
EXCEPTION_DISPOSITION mySEH(struct _EXCEPTION_RECORD* ExceptionRecord,PVOID EstablisherFrame,PCONTEXT pcontext,PVOID DispatcherContext)
{
    if (pcontext->Dr1 != 0 || pcontext->Dr2 != 0 || pcontext->Dr3 != 0 || pcontext->Dr0 != 0)
    {
        printf("SEH验证异常，程序正在被调试,即将退出程序\n");
        ExitProcess(0);
    }
    else
    {
        printf("SEH验证正常\n");
    }
    pcontext->Eip += 3;
​
    return ExceptionContinueExecution;
}
void TestSeh()
{
    printf("test SEH\n");
​
    __asm
    {
        push mySEH
        mov eax,fs:[0]
        push eax
        mov fs:[0],esp
        mov eax, 0
        mov[eax], 1
    }
    cout << "SEH: 跳过了异常代码" << endl;
    cout << "SEH: 程序正常结束" << endl;
}
```
然后通过调试就OK了，当调试器没有选择捕获你这个异常的时候，异常就是交给程序的VEH,SEH，异常过滤器来处理的。

采用VEH来处理：
```text
LONG WINAPI MyPvectoredExceptionHandler(_EXCEPTION_POINTERS* ExceptionInfo)
{
    if (ExceptionInfo->ContextRecord->Dr1 != 0 || ExceptionInfo->ContextRecord->Dr2 != 0 || ExceptionInfo->ContextRecord->Dr3 != 0 || ExceptionInfo->ContextRecord->Dr0 != 0)
    {
        printf("VEH 验证异常，程序正在被调试,即将退出程序\n");
        ExitProcess(0);
    }
    else
    {
        printf("硬件断点的VEH验证正常,无硬件断点\n");
    }
    ExceptionInfo->ContextRecord->Eip += 3;
    return EXCEPTION_CONTINUE_EXECUTION;
}
void TestVeh()
{
    printf("test VEH\n");
    AddVectoredExceptionHandler(1, MyPvectoredExceptionHandler);
    __asm
    {
        mov eax, 0
        mov[eax], 1
    }
    cout << "VEH: 跳过了异常代码" << endl;
    cout << "VEH: 程序正常结束" << endl;
}
```


---

# 四、采用异常实现硬件断点反调试：

如果说直接用前面那种来实现反调试就太辣鸡了，很容易就被识破，但是如果我们添加一个异常呢，这样就会好很多，因为异常要通过一些寄存器，一些不是上面那种直接调用API的办法，会麻烦一点。

采用异常过滤器来处理：

关于异常过滤器可以查看直接的博客：[反调试——异常过滤器 - Sna1lGo - 博客园 (cnblogs.com)](https://link.zhihu.com/?target=https%3A//www.cnblogs.com/Sna1lGo/p/15200377.html)

这里我直接上代码了：
```c
#include"Anti-debugging.h"
LONG WINAPI MyUnhandledExceptionFilter(_EXCEPTION_POINTERS* ExceptionInfo)
{
    if (ExceptionInfo->ContextRecord->Dr0 != 0 || ExceptionInfo->ContextRecord->Dr1 != 0 || ExceptionInfo->ContextRecord->Dr2 != 0 ||
        ExceptionInfo->ContextRecord->Dr3 != 0)
    {
        cout << "Fuck" << endl;
        cout << "异常过滤器验证成功，程序正在被调试" << endl;
        cout << "即将退出进程" << endl;
        ExitProcess(0);
    }
    else
    {
        cout << "异常过滤器验证失败，程序有没有被调试不知道" << endl;
    }
​
    ExceptionInfo->ContextRecord->Eip += 3;
​
    return EXCEPTION_CONTINUE_EXECUTION;
}
​
void MyTestExceptionFilter()
{
    printf("test\n");
    SetUnhandledExceptionFilter(MyUnhandledExceptionFilter);
    int a = 0;
    int b = 2 / a;
    cout << "跳过了异常代码" << endl;
    cout << "程序正常结束" << endl;
}
int main()
{
    MyTestExceptionFilter();
    system("pause");
    return 0;
}
```
这里eip+3的原因是错误代码的硬编码是三个字节，跳过就好了。

---

# 小结

首先需要理解硬件断点的原理，然后通过各种异常验证的时候比对硬件断点是否存在来进行验证。然后就是VEH,SEH，还有异常过滤器的使用方法。今天这个异常过滤器不知道为啥不行，明天再更新来解决这个**异常过滤器**的问题。

---

> 版权声明©：
>
> 本文为 CHA.ATY 的原创文章，遵循 [CC BY-NC-SA 4.0](https://creativecommons.org/licenses/by-sa/4.0/) 许可证进行授权，转载请附上原文出处链接及本声明。
>
> 作者：CHA.ATY
>
> 邮箱：2165150141@qq.com